version: '2'
services:

  # The Application
  app:
    restart: always
    build:
      context: ./
      dockerfile: ../dockerConfig/docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=php-fpm"
      DB_PORT:        "3306"
      DB_HOST:        "database"
  # The Web Server
  web:
    restart: always
    build:
      context: ./
      dockerfile: dockerConfig/docker/web.dockerfile
    working_dir: /var/www
    depends_on:
      - database
      - app
      - mongodb
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  database:
    restart: always
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=ds"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"


  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../data/db/mongo:/data/db
    ports:
      - "27020:27017"
    command: --storageEngine wiredTiger

volumes:
  dbdata:
